import turtle
flag = turtle.Turtle()
screen = turtle.Screen()
screen.title("Flag_Of_Nepal")
flag.hideturtle()
screen.colormode(255)
flag.speed(10)
flag.up()
flag.goto(-350,-500)
def draw_border():
    flag.begin_fill()
    flag.fillcolor(220,20,60)
    flag.down()
    flag.pencolor("blue")
    flag.pensize(10)
    flag.lt(90)
    flag.fd(1000)
    flag.rt(135)
    flag.fd(550)
    flag.rt(135)
    flag.fd(330)
    flag.lt(135)
    flag.fd(600)
    flag.rt(135)
    flag.fd(480)
    flag.end_fill()
def draw_shape():
    flag.pencolor(255,255,255)
    flag.pensize(2)
    flag.up()
    flag.goto(-300,280)
    flag.down()
    flag.lt(105)
    flag.begin_fill()
    flag.fillcolor("white")
    flag.circle(70,150)
    flag.lt(150)
    flag.circle(-92,95)
    flag.end_fill()
    for i in range(12):
        flag.up()
        flag.goto(-230,-120)
        flag.begin_fill()
        flag.setheading(i*30)
        flag.down()
        flag.fd(60)
        flag.rt(150)
        flag.fd(50)
        flag.rt(60)
        flag.fd(60)
        flag.rt(150)
        flag.end_fill()     
draw_border()
draw_shape()    
turtle.mainloop()